import { z } from "zod";

export const checkCatalogIndexEntrySchema = z.object({
  channelCategory: z.string(),
  id: z.string(),
  title: z.string(),
});

export type CheckCatalogIndexEntry = z.infer<
  typeof checkCatalogIndexEntrySchema
>;

/** Slim index for UI; bodies live in catalog.ts. Generated by scripts/generate-check-catalog.ts. */
export const CHECK_CATALOG_INDEX: CheckCatalogIndexEntry[] =
  checkCatalogIndexEntrySchema.array().parse([
    {
      channelCategory: "Food Delivery",
      id: "deliveroo-listing",
      title: "Deliveroo Listing",
    },
    {
      channelCategory: "Food Delivery",
      id: "doordash-listing",
      title: "DoorDash Listing",
    },
    {
      channelCategory: "Social Media",
      id: "facebook-page",
      title: "Has a Facebook page",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing",
      title: "Google Business Profile Listing",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-opening-times",
      title: "Google Business Profile - Opening Hours",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-phone-number",
      title: "Google Business Profile - Phone Number Match",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-photos",
      title: "Google Business Profile - Photo Gallery",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-primary-category",
      title: "Google Business Profile - Primary Category",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-rating",
      title: "Rating ≥ 4.0",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-review-count",
      title: "≥ 20 Google reviews",
    },
    {
      channelCategory: "Google Business Profile",
      id: "google-listing-website-matches",
      title: "Google Business Profile - Website Link Match",
    },
    {
      channelCategory: "Social Media",
      id: "instagram-profile",
      title: "Has an Instagram profile",
    },
    {
      channelCategory: "Social Media",
      id: "linkedin-profile",
      title: "LinkedIn Company Profile",
    },
    {
      channelCategory: "Food Delivery",
      id: "menulog-listing",
      title: "Menulog Listing",
    },
    {
      channelCategory: "Social Media",
      id: "social-profile-banner",
      title: "Social profiles have a banner",
    },
    {
      channelCategory: "Social Media",
      id: "social-profile-freshness",
      title: "Social profiles posted recently",
    },
    {
      channelCategory: "Social Media",
      id: "social-profile-image-match",
      title: "Social profile images match",
    },
    {
      channelCategory: "Social Media",
      id: "tiktok-profile",
      title: "TikTok Business Profile",
    },
    {
      channelCategory: "Food Delivery",
      id: "uber-eats-listing",
      title: "Uber Eats Listing",
    },
    {
      channelCategory: "Website",
      id: "website",
      title: "Uses modern security (HTTPS)",
    },
    {
      channelCategory: "Website",
      id: "website-200-299",
      title: "Website Accessibility - Proper Loading",
    },
    {
      channelCategory: "Website",
      id: "website-ai-visibility",
      title: "AI visibility",
    },
    {
      channelCategory: "Website",
      id: "website-canonical",
      title: "Website SEO - Canonical URLs",
    },
    {
      channelCategory: "Website",
      id: "website-gbp-name-address-phone",
      title: "Website Consistency - NAP Matching",
    },
    {
      channelCategory: "Website",
      id: "website-localbusiness-jsonld",
      title: "Website SEO - Local Business Schema",
    },
    {
      channelCategory: "Website",
      id: "website-menu-jsonld",
      title: "Menu structured data (JSON-LD)",
    },
    {
      channelCategory: "Website",
      id: "website-meta-description",
      title: "Website SEO - Meta Descriptions",
    },
    {
      channelCategory: "Website",
      id: "website-mobile-responsive",
      title: "Is mobile friendly",
    },
    {
      channelCategory: "Website",
      id: "website-og-image",
      title: "Website Social - Open Graph Images",
    },
    {
      channelCategory: "Website",
      id: "website-opening-hours",
      title: "Opening hours printed on the website",
    },
    {
      channelCategory: "Website",
      id: "website-performance",
      title: "Website loads quickly",
    },
    {
      channelCategory: "Website",
      id: "website-physical-address",
      title: "Website Contact - Physical Address Display",
    },
    {
      channelCategory: "Website",
      id: "website-robots",
      title: "Website SEO - Search Engine Access",
    },
    {
      channelCategory: "Website",
      id: "website-sitemap",
      title: "Website SEO - XML Sitemap",
    },
    {
      channelCategory: "Website",
      id: "website-tel-link",
      title: "Website Usability - Click-to-Call Links",
    },
    {
      channelCategory: "Website",
      id: "website-title",
      title: "Title contains business name and suburb/city",
    },
    {
      channelCategory: "Social Media",
      id: "youtube-profile",
      title: "YouTube Business Channel",
    },
  ]);
